version: '3'
services:
  neo4j:
    image: 'neo4j:latest'
    volumes:
      - ./db/plugins:/plugins
      - ./db/data:/data

    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4JLABS_PLUGINS: '["apoc"]'
